# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zmalamud <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/25 13:50:31 by zmalamud          #+#    #+#              #
#    Updated: 2018/01/25 13:50:45 by zmalamud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_tail
SRCS=srcs/*.c

all:
	@gcc $(SRCS) -o $(NAME)

clean:
	@/bin/rm -f *.o

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean re
